# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"
  image: Visual Studio 2015

platform:
  - x64
# Install scripts. (runs after repo cloning)
install:
  - cmd: "chcp 65001"
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - gcc --version
  - g++ --version
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm run build
  # run tests
  - node ./tests/xtest.js 
    # - node ./tests/test.js

# Don't actually build.
build: off
